### JSON body
POST https://localhost:7211/api/user/create
Content-Type: application/json

{
    "firstName": "John",
    "LastName": "Smith",
    "Age": 19
}

### Form fields

### Route parameters
@userId = 0
GET https://localhost:7211/api/user/{{userId}}

### Query parameters

### SPECIAL
### User claims on property with [FromClaim] attribute
### HTTP headers on property with [FromHeader] attribute
### Permissions on property with [HasPermission] attribute