POST https://localhost:7211/api/user/create
Content-Type: application/json

{
    "userId": 1,
    "firstName": "John",
    "LastName": "Smith",
    "Age": 18
}

###

@userId = 0
GET https://localhost:7211/api/user/{{userId}}