POST https://localhost:7211/api/user/create
Content-Type: application/json

{
    "firstName": "J",
    "LastName": "Smith",
    "Age": 17
}

###

@userId = 0
GET https://localhost:7211/api/user/{{userId}}